version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: identity_reconciliation
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: your_username
      DB_PASS: your_password
      DB_NAME: identity_reconciliation
      PORT: 3000